<?php

/**
 * 
 */
function social_media_profiles_add_profile_form($form, &$form_state){
  $form_state['show_add_profile_form'] = TRUE; 
  $form_state['rebuild'] = TRUE;
}

/**
 * 
 */
function social_media_profiles_add_profile_form_submit($form, &$form_state){
  $values = $form_state['values'];

  db_insert('social_media_profiles')
    ->fields(array(
      'label'   => $values['new_profile_label'],
      'url'     => $values['new_profile_url'],
      'fa_icon' => $values['new_profile_fa_icon'],
      'weight'  => $values['new_profile_weight'],
    ))
    ->execute();
  
  $form_state['show_add_profile_form'] = FALSE; 
  $form_state['rebuild'] = TRUE;
}

/**
 * 
 */
function social_media_profiles_delete_profile_form_submit($form, &$form_state){
  $id = $form_state['triggering_element']['#name'];
  
  db_delete('social_media_profiles')
    ->condition('id', $id)
    ->execute();
  
  $form_state['rebuild'] = TRUE;
}

/**
 * 
 */
function social_media_profiles_modify_profiles_callback($form, &$form_state){
  return $form['social_media_profiles'];
}
 
/**
 * implement hook_block_info
 */
function social_media_profiles_block_info() {
  
  $blocks['social_media_profiles'] = array(
    'info' => t('Social Profile Links'),
  );

  return $blocks;
}

/**
 * implement hook_block_view()
 */
function social_media_profiles_block_view($delta = '') {
  $block = array();
  
  switch($delta){
    case 'social_media_profiles':
      $block['subject'] = t('Connect');
      $block['content'] = social_media_profiles_content($delta);
      break;
  }
  
  return $block;
}

function social_media_profiles_content($delta) {
  
  /*
   * Get vars to be used to render content
   */
  $vars = array();
  switch($delta){
    case 'social_media_profiles':
      $vars['profiles'] = db_query('SELECT * FROM social_media_profiles')->fetchAll();
      usort($vars['profiles'], function($a, $b){
        return $a->weight > $b->weight;
      });
      break;
  }
  
  /*
   * Render content using template file
   */
  return theme($delta, $vars);
}

/**
 * Implements hook_form()
 */
function social_media_profiles_form($form, &$form_state) {
  
  $form['social_media_profiles'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social Media Profiles'),
    '#weight' => 10,
    '#collapsible' => FALSE,
    // provide wrapper for AJAX to reload
    '#prefix' => '<div id="wrapper--social-media-profiles">',
    '#suffix' => '</div>',
  );
  
  $form['social_media_profiles']['description'] = array(
    '#markup' => "<p>Go to <a target='_blank' href='http://fontawesome.io/icons#brand'>Font Awesome</a> to find icon classnames.</p>"
  );
  
  $social_profiles = db_query('SELECT * FROM social_media_profiles')->fetchAll();
  usort($social_profiles, function($a, $b){
    return $a->weight > $b->weight;
  });
  
  foreach($social_profiles as $profile){
    $id = $profile->id;
    
    $form['social_media_profiles'][$id] = array(
      '#type' => 'fieldset',
      //'#title' => $profile->label,
    );
    $form['social_media_profiles'][$id][$id.'_id'] = array(
      '#type' => 'hidden',
      '#value' => $profile->id,
    );
    $form['social_media_profiles'][$id][$id.'_weight'] = array(
      '#type' => 'weight',
      '#title' => t('Sort Position'),
      '#default_value' => $profile->weight,
      '#weight' => 10,
    );
    $form['social_media_profiles'][$id][$id.'_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label'),
      '#default_value' => $profile->label,
      '#size' => 15,
      '#maxlength' => 30,
      '#weight' => 20,
    );
    $form['social_media_profiles'][$id][$id.'_url'] = array(
      '#type' => 'textfield',
      '#title' => t('URL'),
      '#default_value' => $profile->url,
      '#size' => 45,
      '#maxlength' => 266,
      '#weight' => 30,
    );
    $form['social_media_profiles'][$id][$id.'_fa_icon'] = array(
      '#type' => 'textfield',
      '#title' => t('Font Awesome icon classname'),
      '#default_value' => $profile->fa_icon,
      '#size' => 15,
      '#maxlength' => 30,
      '#weight' => 40,
    );
    $form['social_media_profiles'][$id][$id.'_delete'] = array(
      '#type' => 'submit',
      '#submit' => array('social_media_profiles_delete_profile_form_submit'),
      '#value' => t('Remove Profile'),
      '#name' => $profile->id,
      '#ajax' => array(
        'callback' => 'social_media_profiles_modify_profiles_callback',
        'wrapper' => 'wrapper--social-media-profiles',
      ),
      '#weight' => 50,
    );
  }
  
  if(!empty($form_state['show_add_profile_form'])){
    $form['social_media_profiles']['new'] = array(
      '#type' => 'fieldset',
      '#title' => t('New Profile'),
    );
    $form['social_media_profiles']['new']['new_profile_weight'] = array(
      '#type' => 'weight',
      '#title' => t('Sort Position'),
      '#weight' => 10,
    );
    $form['social_media_profiles']['new']['new_profile_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label'),
      '#size' => 15,
      '#maxlength' => 30,
      '#weight' => 20,
    );
    $form['social_media_profiles']['new']['new_profile_url'] = array(
      '#type' => 'textfield',
      '#title' => t('URL'),
      '#size' => 45,
      '#maxlength' => 266,
      '#weight' => 30,
    );
    $form['social_media_profiles']['new']['new_profile_fa_icon'] = array(
      '#type' => 'textfield',
      '#title' => t('Font Awesome icon classname'),
      '#default_value' => 'fa-',
      '#size' => 15,
      '#maxlength' => 30,
      '#weight' => 40,
    );
    $form['social_media_profiles']['new']['new_profile_submit'] = array(
      '#type' => 'submit',
      '#submit' => array('social_media_profiles_add_profile_form_submit'),
      '#value' => t('Save New Profile'),
      '#ajax' => array(
        'callback' => 'social_media_profiles_modify_profiles_callback',
        'wrapper' => 'wrapper--social-media-profiles',
      ),
      '#weight' => 50,
    );
  }
  
  if(empty($form_state['show_add_profile_form'])){
    $form['social_media_profiles']['add_profile'] = array(
      '#type' => 'submit',
      '#submit' => array('social_media_profiles_add_profile_form'),
      '#value' => t('Add Profile'),
      '#weight' => 100,
      '#ajax' => array(
        'callback' => 'social_media_profiles_modify_profiles_callback',
        'wrapper' => 'wrapper--social-media-profiles',
      ),
    );
  }
  
  $form['actions'] = array(
    '#weight' => 15,
  );
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 15,
  );
  
  return $form;
}

function social_media_profiles_form_validate($form, &$form_state){
  
}

function social_media_profiles_form_submit($form, &$form_state){
  $values = $form_state['values'];
  
  $profile_ids = social_media_profiles_get_field_ids($form, 'social_media_profiles');
  foreach($profile_ids as $id){
    db_update('social_media_profiles')
      ->fields(array(
        'label'   => $values[$id.'_label'],
        'url'     => $values[$id.'_url'],
        'weight'  => $values[$id.'_weight'],
        'fa_icon' => $values[$id.'_fa_icon'],
      ))
      ->condition('id', $id)
      ->execute();
  }
}

function social_media_profiles_get_field_ids($form, $fieldset){
  $field_ids = array();
  foreach($form[$fieldset] as $key => $value){
    if(is_numeric($key)){
      $field_ids[] = $key;
    }
  }
  return $field_ids;
}

/**
 * Implements hook_menu()
 */
function social_media_profiles_menu() {

  $items = array();

  $items['admin/config/system/social_media_profiles'] = array(
    'title' => 'Contact Information',
    'description' => 'Information for the Connect module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_media_profiles_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of module_preprocess_html()
 */
function social_media_profiles_preprocess_html(&$vars) {
// Add conditional stylesheets for admin pages on admin theme.
  if (current_path() == 'admin/config/system/social_media_profiles') {
    drupal_add_css(drupal_get_path('module', 'social_media_profiles') . '/css/social_media_profiles.css', array('weight' => CSS_THEME));
  }
}

/**
 * Implementation of hook_theme()
 */
function social_media_profiles_theme() {

  $themes['social_media_profiles'] = array(
    'render_element' => 'content',
    'template'  => 'social-media-profiles',
  );
  
  return $themes;
}